//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Modulo10.DataAccess
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MOC10267Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MOC10267Entities object using the connection string found in the 'MOC10267Entities' section of the application configuration file.
        /// </summary>
        public MOC10267Entities() : base("name=MOC10267Entities", "MOC10267Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MOC10267Entities object.
        /// </summary>
        public MOC10267Entities(string connectionString) : base(connectionString, "MOC10267Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MOC10267Entities object.
        /// </summary>
        public MOC10267Entities(EntityConnection connection) : base(connection, "MOC10267Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuario>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuario> _Usuarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Produto> Produtos
        {
            get
            {
                if ((_Produtos == null))
                {
                    _Produtos = base.CreateObjectSet<Produto>("Produtos");
                }
                return _Produtos;
            }
        }
        private ObjectSet<Produto> _Produtos;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarios(Usuario usuario)
        {
            base.AddObject("Usuarios", usuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Produtos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProdutos(Produto produto)
        {
            base.AddObject("Produtos", produto);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Modulo10.DataAccess", Name="Produto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Produto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Produto object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="sKU">Initial value of the SKU property.</param>
        /// <param name="preco">Initial value of the Preco property.</param>
        /// <param name="quantidade">Initial value of the Quantidade property.</param>
        /// <param name="adicionadoEm">Initial value of the AdicionadoEm property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        public static Produto CreateProduto(global::System.Int32 id, global::System.String sKU, global::System.Decimal preco, global::System.Int32 quantidade, global::System.DateTime adicionadoEm, global::System.String nome)
        {
            Produto produto = new Produto();
            produto.Id = id;
            produto.SKU = sKU;
            produto.Preco = preco;
            produto.Quantidade = quantidade;
            produto.AdicionadoEm = adicionadoEm;
            produto.Nome = nome;
            return produto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SKU
        {
            get
            {
                return _SKU;
            }
            set
            {
                OnSKUChanging(value);
                ReportPropertyChanging("SKU");
                _SKU = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SKU");
                OnSKUChanged();
            }
        }
        private global::System.String _SKU;
        partial void OnSKUChanging(global::System.String value);
        partial void OnSKUChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Preco
        {
            get
            {
                return _Preco;
            }
            set
            {
                OnPrecoChanging(value);
                ReportPropertyChanging("Preco");
                _Preco = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Preco");
                OnPrecoChanged();
            }
        }
        private global::System.Decimal _Preco;
        partial void OnPrecoChanging(global::System.Decimal value);
        partial void OnPrecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Quantidade
        {
            get
            {
                return _Quantidade;
            }
            set
            {
                OnQuantidadeChanging(value);
                ReportPropertyChanging("Quantidade");
                _Quantidade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantidade");
                OnQuantidadeChanged();
            }
        }
        private global::System.Int32 _Quantidade;
        partial void OnQuantidadeChanging(global::System.Int32 value);
        partial void OnQuantidadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AdicionadoEm
        {
            get
            {
                return _AdicionadoEm;
            }
            set
            {
                OnAdicionadoEmChanging(value);
                ReportPropertyChanging("AdicionadoEm");
                _AdicionadoEm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AdicionadoEm");
                OnAdicionadoEmChanged();
            }
        }
        private global::System.DateTime _AdicionadoEm;
        partial void OnAdicionadoEmChanging(global::System.DateTime value);
        partial void OnAdicionadoEmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Modulo10.DataAccess", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="senha">Initial value of the Senha property.</param>
        public static Usuario CreateUsuario(global::System.Int32 id, global::System.String email, global::System.String senha)
        {
            Usuario usuario = new Usuario();
            usuario.Id = id;
            usuario.Email = email;
            usuario.Senha = senha;
            return usuario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Senha
        {
            get
            {
                return _Senha;
            }
            set
            {
                OnSenhaChanging(value);
                ReportPropertyChanging("Senha");
                _Senha = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Senha");
                OnSenhaChanged();
            }
        }
        private global::System.String _Senha;
        partial void OnSenhaChanging(global::System.String value);
        partial void OnSenhaChanged();

        #endregion
    
    }

    #endregion
    
}
